import Sidebar from '@/components/ui/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Audiowide } from 'next/font/google'

const audiowide = Audiowide({ subsets: ['latin'] , weight: ['400']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${audiowide.className} bg-black`}>
      <Sidebar/>
        {children}
      </body>
    </html>
  )
}
