name: Lint and Format Backend

on:
  push:
    branches:
      - main  # You can adjust this to your main branch

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: |
          cd backend
          npm install

			- name: Format
				run: |
          cd backend
          npm run format

      - name: Lint
        run: npm run lint
