name: Run Unit Integration and E2E tests

on:
  push:
    branches:
      - main

jobs:
  unit-integration-and-e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Unit and Integration tests
        run: |
          cd backend
          npm run test:coverage

      - name: E2E tests
        run: |
          cd backend
          npm run test:e2e:coverage

      - name: Coveralls GitHub Action (Backend)
        uses: coverallsapp/github-action@v2
        with:
          files: ./backend/coverage/e2e/lcov.info ./backend/coverage/testing/lcov.info
          allow-empty: true


